# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1288/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1288/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anatoly/Documents/HW5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anatoly/Documents/HW5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1288/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1288/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anatoly/Documents/HW5/CMakeFiles /home/anatoly/Documents/HW5//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anatoly/Documents/HW5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw5

# Build rule for target.
hw5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hw5
.PHONY : hw5

# fast build rule for target.
hw5/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/build
.PHONY : hw5/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named hw5.tar

# Build rule for target.
hw5.tar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hw5.tar
.PHONY : hw5.tar

# fast build rule for target.
hw5.tar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.tar.dir/build.make CMakeFiles/hw5.tar.dir/build
.PHONY : hw5.tar/fast

Event.o: Event.cc.o
.PHONY : Event.o

# target to build an object file
Event.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/Event.cc.o
.PHONY : Event.cc.o

Event.i: Event.cc.i
.PHONY : Event.i

# target to preprocess a source file
Event.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/Event.cc.i
.PHONY : Event.cc.i

Event.s: Event.cc.s
.PHONY : Event.s

# target to generate assembly for a file
Event.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/Event.cc.s
.PHONY : Event.cc.s

Schedule.o: Schedule.cc.o
.PHONY : Schedule.o

# target to build an object file
Schedule.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/Schedule.cc.o
.PHONY : Schedule.cc.o

Schedule.i: Schedule.cc.i
.PHONY : Schedule.i

# target to preprocess a source file
Schedule.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/Schedule.cc.i
.PHONY : Schedule.cc.i

Schedule.s: Schedule.cc.s
.PHONY : Schedule.s

# target to generate assembly for a file
Schedule.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/Schedule.cc.s
.PHONY : Schedule.cc.s

test.o: test.cc.o
.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i
.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s
.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.s
.PHONY : test.cc.s

translate.o: translate.cc.o
.PHONY : translate.o

# target to build an object file
translate.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/translate.cc.o
.PHONY : translate.cc.o

translate.i: translate.cc.i
.PHONY : translate.i

# target to preprocess a source file
translate.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/translate.cc.i
.PHONY : translate.cc.i

translate.s: translate.cc.s
.PHONY : translate.s

# target to generate assembly for a file
translate.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hw5.dir/build.make CMakeFiles/hw5.dir/translate.cc.s
.PHONY : translate.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hw5.tar"
	@echo "... hw5"
	@echo "... test"
	@echo "... Event.o"
	@echo "... Event.i"
	@echo "... Event.s"
	@echo "... Schedule.o"
	@echo "... Schedule.i"
	@echo "... Schedule.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... translate.o"
	@echo "... translate.i"
	@echo "... translate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

